Repository Maryssun/SAP007-burger-queen-api-client, pull requests merged in 2022-05, with the labels that each got.

#1 fix:creation-login-page
  package-lock.json
  src/App.js
  src/components/InputsLogin.js
  src/imgs/LOGO QUEEN.png
  src/index.js
Labels: fix

#2 feat:create-routes
  react-rotas/.gitignore
  react-rotas/README.md
  react-rotas/package-lock.json
  react-rotas/package.json
  react-rotas/public/favicon.ico
  react-rotas/public/index.html
  react-rotas/public/logo192.png
  react-rotas/public/logo512.png
  react-rotas/public/manifest.json
  react-rotas/public/robots.txt
  react-rotas/src/App.css
  react-rotas/src/App.js
  react-rotas/src/App.test.js
  react-rotas/src/index.css
  react-rotas/src/index.js
  react-rotas/src/logo.svg
  react-rotas/src/reportWebVitals.js
  react-rotas/src/setupTests.js
Labels: feat, fix

#7 fix: Criação layout regiter e login
  src/components/Button/button.style.module.css
  src/components/Button/index.jsx
  src/components/Input/index.jsx
  src/components/Input/input.style.module.css
  src/components/Select/index.jsx
  src/components/Select/select.style.module.css
  src/pages/Login/index.jsx
  src/pages/Login/login.style.module.css
  src/pages/Register/index.jsx
  src/pages/Register/register.style.module.css
Labels: feat, fix

#8 feat: API e auth
  src/appSettings.js
  src/components/Button/index.jsx
  src/components/Input/index.jsx
  src/components/Select/index.jsx
  src/components/Select/select.style.module.css
  src/pages/Hall/hall.style.module.css
  src/pages/Hall/index.jsx
  src/pages/Kitchen/index.jsx
  src/pages/Kitchen/kitchen.style.module.css
  src/pages/Login/index.jsx
  src/pages/Login/login.style.module.css
  src/routes.js
  src/services/auth.service.js
  src/services/user.service.js
Labels: feat

#9 API connection to registration page
  package-lock.json
  src/assets/images/batata.png
  src/assets/images/burguer-queen.png
  src/assets/images/cafe-leite.png
  src/assets/images/cafe.png
  src/assets/images/copo-agua.png
  src/assets/images/editar.png
  src/assets/images/garrafa-agua.png
  src/assets/images/ham-duplo.png
  src/assets/images/ham-simples.png
  src/assets/images/lixeira.png
  src/assets/images/onion.png
  src/assets/images/refri-g.png
  src/assets/images/refri-m.png
  src/assets/images/sanduiche.png
  src/assets/images/suco.png
  src/components/Button/index.jsx
  src/components/Select/index.jsx
  src/pages/Login/index.jsx
  src/pages/Register/index.jsx
  src/routes.js
  src/services/Token.js
  src/services/user.service.js
Labels: bug, refactoring, feat

#12 feat: page styling
  src/assets/images/LogoQueen30.png
  src/assets/images/LogoQueen40.png
  src/assets/images/burguerQueen.png
  src/components/Button/button.style.module.css
  src/components/Input/input.style.module.css
  src/components/Radio/index.jsx
  src/components/Radio/radio.style.module.css
  src/global.style.module.css
  src/pages/Login/index.jsx
  src/pages/Login/login.style.module.css
  src/pages/Register/index.jsx
  src/pages/Register/register.style.module.css
  src/services/user.service.js
Labels: refactoring, feat, fix

#15 Feat/criacao select
  src/components/Select/index.jsx
  src/components/Select/select.style.module.css
  src/pages/Register/index.jsx
Labels: feat
